import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { DEFAULT_ENCODER, encodeTicket, hex } from '../../src/lib/escpos';
import { invoiceItems, invoiceLines, invoiceTicketData, type InvoiceBill, type InvoiceIdentity } from '../../src/lib/invoice';
import {
  PAPER,
  bigColsFor,
  buildTicket,
  defaultTemplate,
  rowMode,
  type PaperWidth,
  type TemplateConfig,
  type TicketData,
} from '../../src/lib/print-template';
import { composeTicket } from '../../src/lib/ticket-compose';
import { previewKotData, ticketPreview } from '../../src/lib/ticket-preview';
import { testBill } from '../../src/lib/test-ticket';
import { rawPrintDll, RAW_PRINT_SCRIPT, rawPrintFits } from '../../bridge/src/transport/windows-queue';

/**
 * The 25-Sep correction list, printing items 3-9, 13 and 14 - executed.
 *
 * Every case here is about the paper: the order of its lines, where its columns end, whether a
 * big line fits the roll, whether the preview is the print, and which rows a template prints.
 */

const code = (p: string): string => readFileSync(p, 'utf8');

const WHO: InvoiceIdentity = { name: 'Jalsa Restaurant', address: 'Bagalur Road, Hosur', phone: '04344 000000', gstin: '33ABCDE1234F1Z5', upiId: '' };

const item = (name: string, qty: number, unitPrice: number, foodType: 'veg' | 'non_veg' | 'egg' = 'veg', cancelledAt: string | null = null) => ({
  name,
  qty,
  unitPrice,
  foodType,
  category: 'Mains',
  cancelledAt,
});

const BILL: InvoiceBill = {
  code: 'B-1044',
  hostTable: 'A5',
  tables: ['A5'],
  captain: 'Ravi',
  openedAt: '2026-09-24T13:00:00Z',
  closedAt: '2026-09-24T14:35:00Z',
  discountPct: 0,
  discountAmount: 50,
  taxRate: 5,
  paymentMode: 'UPI',
  kots: [
    { status: 'served', items: [item('Paneer Butter Masala', 1, 280), item('Butter Naan', 12, 45), item('Chicken 65', 2, 260, 'non_veg')] },
    { status: 'cancelled', items: [item('Mutton Biryani', 1, 380, 'non_veg')] },
    { status: 'served', items: [item('Egg Curry', 1, 180, 'egg'), item('Sweet Lassi', 2, 90, 'veg', '2026-09-24T14:00:00Z'), item('Gulab Jamun', 3, 70)] },
  ],
};

/* ── Item 3: order ─────────────────────────────────────────────────────── */

test('item 3: the ticket reads a round in cart order - line_seq breaks the created_at tie', () => {
  const payload = code('src/lib/db/bridge-payload.ts');
  expect(payload).toMatch(/\.order\('created_at', \{ ascending: true \}\)\s*\.order\('line_seq', \{ ascending: true \}\)/);
  const migration = code('supabase/migrations/20260925090000_jalsa_kot_item_line_order.sql');
  expect(migration).toContain('add column if not exists line_seq bigint generated by default as identity');
});

test('item 3: the bill read sorts each round by line_seq and rounds by time, not by code as text', () => {
  const q = code('src/lib/db/queries.ts');
  expect(q).toContain('menu_category_name, line_seq )');
  expect(q).toContain('items: sortByLineSeq(');
  expect(q).toContain('a.createdAt.localeCompare(b.createdAt) || a.code.localeCompare(b.code)');
});

test('item 3: sortByLineSeq keeps cart order whatever order the rows arrive in', async () => {
  // Imported lazily: queries.ts is server-only, so only the pure helper is exercised - by reading
  // its body and running it.
  const src = code('src/lib/db/queries.ts');
  const body = src.slice(src.indexOf('export function sortByLineSeq'), src.indexOf('interface RawRef'));
  expect(body).toContain('[...rows].sort((a, b) => seq(a) - seq(b))');
  const rows = [{ line_seq: 7, n: 'c' }, { line_seq: 5, n: 'a' }, { line_seq: 6, n: 'b' }];
  const seq = (r: { line_seq: number }): number => r.line_seq;
  expect([...rows].sort((a, b) => seq(a) - seq(b)).map((r) => r.n)).toEqual(['a', 'b', 'c']);
});

test('item 3: the invoice keeps the order things were ordered in, across rounds, and drops what was cancelled', () => {
  expect(invoiceItems(BILL).map((i) => i.name)).toEqual(['Paneer Butter Masala', 'Butter Naan', 'Chicken 65', 'Egg Curry', 'Gulab Jamun']);
  const printed = invoiceLines(BILL, WHO, '80', undefined).map((l) => l.text);
  const at = (n: string): number => printed.findIndex((t) => t.startsWith(n));
  expect(at('Paneer Butter Masala')).toBeLessThan(at('Butter Naan'));
  expect(at('Butter Naan')).toBeLessThan(at('Chicken 65'));
  expect(at('Chicken 65')).toBeLessThan(at('Egg Curry'));
  expect(at('Egg Curry')).toBeLessThan(at('Gulab Jamun'));
});

/* ── Items 4, 5: the bill's structure and alignment ────────────────────── */

for (const width of ['58', '80'] as PaperWidth[]) {
  test(`items 4-5: ${width} mm - every figure column ends at the paper's edge, under its heading`, () => {
    const cols = PAPER[width].cols.normal;
    const lines = invoiceLines(BILL, WHO, width, undefined);
    const plain = lines.filter((l) => l.weight !== 'big');
    // Nothing is wider than the roll; nothing big is wider than half of it.
    for (const l of lines) expect(l.text.length, l.text).toBeLessThanOrEqual(l.weight === 'big' ? bigColsFor(cols) : cols);
    const header = plain.find((l) => l.text.startsWith('ITEM'));
    expect(header?.weight).toBe('bold');
    expect(header?.text.length).toBe(cols);
    expect(header?.text.endsWith('AMOUNT')).toBe(true);
    expect(header?.text).toContain('QTY');
    expect(header?.text).toContain('RATE');
    // Every item row: its amount ends at the last column, its qty ends where QTY ends.
    const qtyEnd = (header?.text.indexOf('QTY') ?? 0) + 3;
    for (const name of ['Paneer', 'Butter Naan', 'Chicken 65', 'Egg Curry', 'Gulab Jamun']) {
      const row = plain.find((l) => l.text.startsWith(name.slice(0, 6)) && /\d$/.test(l.text));
      expect(row, name).toBeTruthy();
      expect(row!.text.length, name).toBe(cols);
      expect(row!.text[qtyEnd - 1], `${name}: qty right-aligned under QTY`).toMatch(/\d/);
    }
    const naan = plain.find((l) => l.text.startsWith('Butter Naan'))!.text;
    expect(naan.endsWith('540')).toBe(true);
    // Totals: labels left, figures right, at the same edge.
    for (const label of ['SUBTOTAL', 'DISCOUNT', 'CGST', 'SGST']) {
      const row = plain.find((l) => l.text.startsWith(label));
      expect(row, label).toBeTruthy();
      expect(row!.text.length, label).toBe(cols);
    }
    const total = lines.find((l) => l.text.startsWith('TOTAL'));
    expect(total?.weight).toBe('big');
    expect(total?.text.length).toBe(bigColsFor(cols));
  });
}

test('items 4-5: restaurant, invoice facts, items, totals, payment and footer, in that order', () => {
  const texts = invoiceLines(BILL, WHO, '80', undefined).map((l) => l.text.trim());
  const order = ['JALSA RESTAURANT', 'GSTIN 33ABCDE1234F1Z5', 'TAX INVOICE', 'BILL NO', 'TABLE', 'DATE', 'TIME', 'ITEM', 'SUBTOTAL', 'DISCOUNT', 'CGST', 'TOTAL', 'PAID BY', 'THANK YOU'];
  const idx = order.map((o) => texts.findIndex((t) => t.startsWith(o)));
  idx.forEach((v, i) => expect(v, order[i]).toBeGreaterThan(-1));
  expect([...idx].sort((a, b) => a - b)).toEqual(idx);
  expect(texts).toContain('Bagalur Road, Hosur');
  expect(texts.find((t) => t.startsWith('CGST'))).toContain('@2.5%');
});

test('item 5: the totals are the owner screen totals - the cancelled round is not charged', () => {
  const data = invoiceTicketData(BILL, WHO);
  // 280 + 540 + 520 + 180 + 210 = 1730; -50 = 1680; 5% = 84.
  expect(data.totals).toMatchObject({ subtotal: 1730, discount: 50, tax: 84, payable: 1764 });
  expect(invoiceLines(BILL, WHO, '80', undefined).map((l) => l.text)).not.toContainEqual(expect.stringContaining('Mutton Biryani'));
});

test('item 8: an invoice is dated when the bill was closed, on the restaurant clock', () => {
  const data = invoiceTicketData(BILL, WHO);
  expect(data.date).toBe('24 Sep 2026');
  expect(data.time).toBe('8:05 pm');
});

/* ── Item 5: big lines on the KOT ──────────────────────────────────────── */

test('item 5: a big line is laid out for a doubled character - it fits the roll, on both widths', () => {
  for (const width of ['58', '80'] as PaperWidth[]) {
    const cols = PAPER[width].cols.normal;
    const kot = buildTicket('kot', previewKotData([], WHO), defaultTemplate('kot', width), { reprint: true });
    for (const l of kot.filter((x) => x.weight === 'big')) expect(l.text.length * 2, l.text).toBeLessThanOrEqual(cols);
  }
});

/* ── Item 7: the printable width, no left margin ───────────────────────── */

test('item 7: with area on, the encoder sets left margin 0 and the full printable width, then the font', () => {
  const lines = [{ text: 'X', weight: 'plain' as const }];
  const h80 = hex(encodeTicket(lines, { ...DEFAULT_ENCODER, width: '80', area: true }));
  expect(h80.startsWith('1B 40 1B 74 00 1D 4C 00 00 1D 57 40 02 1B 4D 00')).toBe(true); // 576 dots
  const h58 = hex(encodeTicket(lines, { ...DEFAULT_ENCODER, width: '58', area: true, font: 'small' }));
  expect(h58.startsWith('1B 40 1B 74 00 1D 4C 00 00 1D 57 80 01 1B 4D 01')).toBe(true); // 384 dots, font B
  // Off by default: every pinned golden keeps its bytes.
  expect(hex(encodeTicket(lines, DEFAULT_ENCODER)).startsWith('1B 40 1B 74 00 58')).toBe(true);
});

test('item 7: the bridge turns the area on and passes the font; the templates carry no left margin', () => {
  expect(code('bridge/src/loop.ts')).toMatch(/area: true,\s*\.\.\.\(claim\.payload\.font \? \{ font: claim\.payload\.font \} : \{\}\)/);
  expect(defaultTemplate('kot').marginLeftMm).toBe(0);
  expect(defaultTemplate('bill').marginLeftMm).toBe(0);
});

/* ── Items 8, 9: one invoice; the preview is the print ─────────────────── */

test('item 8: the printed invoice, the preview and the browser copy all come from invoice.ts', () => {
  expect(code('src/lib/db/bridge-payload.ts')).toContain('invoiceTicketData(bill, {');
  expect(code('src/lib/ticket-preview.ts')).toContain('lines: invoiceLines(bill, input.who, input.width, input.template, input.now)');
  expect(code('src/features/owner/sections/Payments.tsx')).toContain('bill: bill.invoice,');
  const sheet = code('src/features/owner/BillDetailSheet.tsx');
  expect(sheet).toContain('className="j-print-root hidden print:block"');
  expect(sheet).toContain("invoice ? 'print:hidden' : 'j-print-root'");
});

test('item 9: the bill preview is byte-for-byte what composeTicket prints for that bill at that width', () => {
  const template: Partial<TemplateConfig> = { separator: 'equals' };
  for (const width of ['58', '80'] as PaperWidth[]) {
    const now = new Date('2026-09-24T15:00:00Z');
    const preview = ticketPreview({ kind: 'bill', width, template, menu: [], who: WHO, taxRate: 5, bill: BILL, now });
    const { items, totals, upiId, station: _s, ...header } = invoiceTicketData(BILL, WHO, now);
    void _s;
    void upiId;
    const printed = composeTicket({
      job: { id: 'j', kind: 'bill', printerId: 'c', station: 'Billing', foodSide: 'all', isReprint: false },
      width,
      template,
      printers: [],
      splitByFoodType: false,
      header,
      items,
      ...(totals ? { totals } : {}),
    });
    if (!printed.ok) throw new Error(printed.blocked);
    expect(hex(encodeTicket(preview.lines, { ...DEFAULT_ENCODER, width }))).toBe(hex(encodeTicket(printed.lines, { ...DEFAULT_ENCODER, width })));
    expect(preview.cols).toBe(PAPER[width].cols.normal);
  }
});

test('item 9: a KOT preview uses the machine width, not the width saved on the template', () => {
  const saved: Partial<TemplateConfig> = { width: '80' };
  const p58 = ticketPreview({ kind: 'kot', width: '58', template: saved, menu: [{ id: 'm', name: 'Paneer Tikka', price: 240, foodType: 'veg', category: 'Starters' }], who: WHO, taxRate: 5 });
  expect(p58.cols).toBe(PAPER['58'].cols.normal);
  for (const l of p58.lines) expect(l.text.length).toBeLessThanOrEqual(PAPER['58'].cols.normal);
});

test('item 9: Preview | Test Print sit beside each other for a kitchen ticket or a bill', () => {
  const screen = code('src/features/owner/sections/PrintersSection.tsx');
  expect(screen).toContain('owner-printers-kind-kot-');
  expect(screen).toContain('owner-printers-kind-bill-');
  expect(screen).toContain('owner-printers-preview-');
  expect(screen).toContain("{ action: 'test-print', printerId: p.id, ticket }");
  expect(code('src/lib/db/bridge-payload.ts')).toContain("const TEST_BILL_KIND = 'TestBill';");
  // The bill test print is laid out by the same invoice builder as a guest's bill.
  const lines = invoiceLines(testBill(5, new Date('2026-09-24T15:00:00Z')), WHO, '80', undefined).map((l) => l.text);
  expect(lines.some((t) => t.includes('TEST PRINT'))).toBe(true);
  expect(lines.some((t) => t.startsWith('ITEM') && t.endsWith('AMOUNT'))).toBe(true);
});

/* ── Item 6: speed ─────────────────────────────────────────────────────── */

test('item 6: the bridge drains waiting tickets, idles at 4 s at most, and prints before it rescans', () => {
  const svc = code('bridge/src/service.ts');
  expect(svc).toContain('const pollMs = opts.pollMs ?? 2_000;');
  expect(svc).toContain('const maxBackoffMs = opts.maxBackoffMs ?? 4_000;');
  expect(svc).toMatch(/cycle\.eligible > 1\s*\?\s*0/);
  expect(svc.indexOf('cycle = await runCycle(')).toBeLessThan(svc.indexOf('if (!synced && syncDue(current))'));
});

test('item 6: the print class is compiled once into the spool and loaded after that', () => {
  expect(RAW_PRINT_SCRIPT).toContain('-OutputAssembly $dll');
  expect(RAW_PRINT_SCRIPT).toContain('Add-Type -LiteralPath $dll');
  expect(RAW_PRINT_SCRIPT).toContain('if (-not $loaded) { Add-Type -TypeDefinition $src }');
  expect(rawPrintFits()).toBe(true);
  expect(rawPrintDll('C:\\spool')).toMatch(/jalsa-raw-print-[0-9a-f]{12}\.dll$/);
});

/* ── Items 13, 14: KOT rows ────────────────────────────────────────────── */

const KOT_DATA: TicketData = { ...previewKotData([{ id: 'm', name: 'Paneer Tikka', price: 240, foodType: 'veg', category: 'Starters' }], WHO), customer: '', note: '' };

test('item 13: a KOT carries neither the restaurant address nor its phone by default', () => {
  const texts = buildTicket('kot', KOT_DATA, defaultTemplate('kot')).map((l) => l.text.trim());
  expect(texts).not.toContain(WHO.address);
  expect(texts).not.toContain(WHO.phone);
});

test('item 14: Off never prints; On prints only a value; Always on prints "-" when empty', () => {
  const base = defaultTemplate('kot');
  const withMode = (mode: 'off' | 'on' | 'always'): string[] =>
    buildTicket('kot', KOT_DATA, { ...base, modes: { customer: mode } }).map((l) => l.text);
  expect(withMode('off').some((t) => t.startsWith('GUEST'))).toBe(false);
  expect(withMode('on').some((t) => t.startsWith('GUEST'))).toBe(false); // empty, so not printed
  const always = withMode('always').find((t) => t.startsWith('GUEST'));
  expect(always?.trim().endsWith('-')).toBe(true);
  const named = buildTicket('kot', { ...KOT_DATA, customer: 'Priya' }, { ...base, modes: { customer: 'on' } }).map((l) => l.text);
  expect(named.find((t) => t.startsWith('GUEST'))?.endsWith('Priya')).toBe(true);
});

test('item 14: a mode wins over the old on/off, a locked row is always on, and an old template reads as before', () => {
  const base = defaultTemplate('kot');
  expect(rowMode({ ...base, on: { ...base.on, phone: true }, modes: { phone: 'off' } }, 'phone')).toBe('off');
  expect(rowMode({ ...base, modes: { source: 'off' } }, 'source')).toBe('always');
  expect(rowMode({ ...base, on: { ...base.on, table: false } }, 'table')).toBe('off');
  expect(rowMode({ ...base, on: { ...base.on, table: true } }, 'table')).toBe('on');
});

test('item 14: a KOT row mode never reaches the bill - each kind has its own template', () => {
  const bill = invoiceLines(BILL, WHO, '80', { modes: {} }).map((l) => l.text);
  const kotModes = { ...defaultTemplate('kot'), modes: { table: 'off' as const, date: 'off' as const } };
  // Setting KOT modes changes the KOT...
  expect(buildTicket('kot', KOT_DATA, kotModes).some((l) => l.text.startsWith('TABLE'))).toBe(false);
  // ...and the bill, composed from its own template, still prints both.
  expect(bill.some((t) => t.startsWith('TABLE'))).toBe(true);
  expect(bill.some((t) => t.startsWith('DATE'))).toBe(true);
  const panel = code('src/features/owner/sections/PrintSetupSection.tsx');
  expect(panel).toContain("value: { [kind]: config },");
  expect(panel).toContain('owner-print-field-${key}-${m}');
});
