/* GENERATED by scripts/theme-build.mjs from design/tokens.json - DO NOT EDIT. */
/* Rebuild: npm run theme:build */

/** Every semantic colour role in the design system. */
export const semanticTokens = [
  'background',
  'surface',
  'surfaceRaised',
  'surfaceSunken',
  'text.heading',
  'text.body',
  'text.muted',
  'text.inverse',
  'text.disabled',
  'text.link',
  'text.linkHover',
  'primary',
  'primaryHover',
  'primaryPressed',
  'onPrimary',
  'primarySurface',
  'onPrimarySurface',
  'secondary',
  'onSecondary',
  'accent',
  'onAccent',
  'border',
  'borderStrong',
  'borderFocus',
  'error',
  'onError',
  'errorSurface',
  'onErrorSurface',
  'success',
  'onSuccess',
  'successSurface',
  'onSuccessSurface',
  'warning',
  'onWarning',
  'warningSurface',
  'onWarningSurface',
  'info',
  'onInfo',
  'infoSurface',
  'onInfoSurface',
  'overlay',
  'skeleton',
  'foodType.veg',
  'foodType.nonVeg',
  'foodType.egg',
] as const;
export type SemanticToken = (typeof semanticTokens)[number];

/** CSS custom-property name for a token. */
export const cssVarFor = (t: SemanticToken): string =>
  '--' + t.replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** `var(--x)` reference, for style props and CSS-in-JS. Prefer this in the DOM. */
export const v = (t: SemanticToken): string => `var(${cssVarFor(t)})`;

/** Resolved values per theme. Use ONLY where a real value is required (canvas, charts,
 *  `<meta name="theme-color">`, native platforms). */
export const themeValues = {
  light: {
    'background': '#EDE7E4',
    'surface': '#FFFFFF',
    'surfaceRaised': '#FFFFFF',
    'surfaceSunken': '#F4F0EE',
    'text.heading': '#201C1B',
    'text.body': '#241F1E',
    'text.muted': '#665D59',
    'text.inverse': '#FFFFFF',
    'text.disabled': '#8B827E',
    'text.link': '#7A1C24',
    'text.linkHover': '#5E1319',
    'primary': '#7A1C24',
    'primaryHover': '#5E1319',
    'primaryPressed': '#4A0E13',
    'onPrimary': '#FFFFFF',
    'primarySurface': '#FBF1F0',
    'onPrimarySurface': '#7A1C24',
    'secondary': '#4F6136',
    'onSecondary': '#FFFFFF',
    'accent': '#8A5A10',
    'onAccent': '#FFFFFF',
    'border': '#E0D8D5',
    'borderStrong': '#6E645F',
    'borderFocus': '#7A1C24',
    'error': '#A81D19',
    'onError': '#FFFFFF',
    'errorSurface': '#FDECEC',
    'onErrorSurface': '#8C1714',
    'success': '#166A2E',
    'onSuccess': '#FFFFFF',
    'successSurface': '#E4F3E8',
    'onSuccessSurface': '#14602A',
    'warning': '#8A5A10',
    'onWarning': '#FFFFFF',
    'warningSurface': '#FFF1DC',
    'onWarningSurface': '#6B4A12',
    'info': '#1B4E8F',
    'onInfo': '#FFFFFF',
    'infoSurface': '#EAF1FB',
    'onInfoSurface': '#16437C',
    'overlay': 'rgba(36,31,30,0.46)',
    'skeleton': '#E4DCD9',
    'foodType.veg': '#1B7A36',
    'foodType.nonVeg': '#B31C19',
    'foodType.egg': '#8A5A10',
  },
  dark: {
    'background': '#1A1614',
    'surface': '#241F1E',
    'surfaceRaised': '#2E2826',
    'surfaceSunken': '#0F0D0C',
    'text.heading': '#FFFFFF',
    'text.body': '#F2EAE7',
    'text.muted': '#BCB0AC',
    'text.inverse': '#1A1614',
    'text.disabled': '#8A7F7B',
    'text.link': '#FFD9A0',
    'text.linkHover': '#FFE8C4',
    'primary': '#FFD9A0',
    'primaryHover': '#FFE6BC',
    'primaryPressed': '#F5C880',
    'onPrimary': '#241F1E',
    'primarySurface': '#3A2A28',
    'onPrimarySurface': '#FFD2AC',
    'secondary': '#A8C98F',
    'onSecondary': '#17210F',
    'accent': '#FFD9A0',
    'onAccent': '#241F1E',
    'border': '#3A3230',
    'borderStrong': '#93867F',
    'borderFocus': '#FFD9A0',
    'error': '#FF9A93',
    'onError': '#2A100E',
    'errorSurface': '#3A1A18',
    'onErrorSurface': '#FFB3AD',
    'success': '#7BD68F',
    'onSuccess': '#06230E',
    'successSurface': '#16301C',
    'onSuccessSurface': '#9BE2AB',
    'warning': '#FFC96B',
    'onWarning': '#2A1C05',
    'warningSurface': '#362605',
    'onWarningSurface': '#FFD89A',
    'info': '#8FB8F0',
    'onInfo': '#0A1A2E',
    'infoSurface': '#16233A',
    'onInfoSurface': '#AFCDF6',
    'overlay': 'rgba(0,0,0,0.7)',
    'skeleton': '#2C2523',
    'foodType.veg': '#7BD68F',
    'foodType.nonVeg': '#FF9A93',
    'foodType.egg': '#FFD9A0',
  },
} as const;

export type ThemeName = keyof typeof themeValues;

export const scales = {
  radius: {"none":"0px","sm":"10px","md":"16px","lg":"20px","xl":"26px","pill":"9999px"},
  spacing: {"0":"0px","1":"4px","2":"8px","3":"12px","4":"16px","5":"22px","6":"30px","7":"44px","8":"64px"},
  typography: {"fontFamilyBase":"var(--font-body), 'Noto Sans', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif","fontFamilyMono":"ui-monospace, SFMono-Regular, Menlo, Consolas, monospace","size":{"caption":"11.5px","body":"13px","bodyLg":"15px","h3":"17px","h2":"21px","h1":"26px","hero":"34px"},"lineHeight":{"caption":"16px","body":"19px","bodyLg":"22px","h3":"23px","h2":"27px","h1":"32px","hero":"40px"},"weight":{"body":"400","medium":"500","subheading":"600","heading":"700"}},
  motion: {"duration":{"instant":"90ms","fast":"160ms","base":"260ms","slow":"420ms"},"easing":{"out":"cubic-bezier(0.16,1,0.3,1)","inOut":"cubic-bezier(0.65,0,0.35,1)","in":"cubic-bezier(0.55,0,1,0.45)"},"note":"Every animation must collapse to its END STATE under prefers-reduced-motion. Motion never gates interactivity."},
  layout: {"minSupportedWidth":"320px","contentMaxWidth":"1240px","guestMaxWidth":"430px","minTouchTarget":"44px","bottomChromeHeight":"58px","bottomChromeClearance":"74px","guestHeaderHeight":"68px","ownerRequestsMaxHeight":"14.5rem"},
} as const;

/** Declared theme-aware assets, rendered by <ThemedImage />. */
export const themedAssets = {
  "logo.primary": {
    "light": "/brand/logo-light.svg",
    "dark": "/brand/logo-dark.svg",
    "alt": "Jalsa wordmark used in the app header and on printed artefacts"
  },
  "logo.mark": {
    "light": "/brand/mark-light.svg",
    "dark": "/brand/mark-dark.svg",
    "alt": "Jalsa square mark / PWA icon source"
  },
  "illustration.empty": {
    "light": "/brand/empty-light.svg",
    "dark": "/brand/empty-dark.svg",
    "alt": "Empty-state illustration"
  },
  "og.social": {
    "light": "/brand/og-card.png",
    "dark": "/brand/og-card.png",
    "alt": "Open Graph / social preview card. Fixed to the light artwork on purpose: social platforms render it on their own canvas, so it must not follow the viewer theme."
  },
  "logo.badge": {
    "light": "/brand/jalsa-badge.png",
    "dark": "/brand/jalsa-badge.png",
    "alt": "The restaurant's own printed badge — the maroon tile carried on the tabletop QR stand, the bill and the HR documents."
  }
} as const;
