/* GENERATED by scripts/theme-build.mjs from ../../design/tokens.json - DO NOT EDIT. */
/* Rebuild: npm run theme:build */

/** Every semantic colour role in the design system. */
export const semanticTokens = [
  'background',
  'surface',
  'surfaceRaised',
  'surfaceSunken',
  'text.heading',
  'text.body',
  'text.muted',
  'text.inverse',
  'text.disabled',
  'text.link',
  'text.linkHover',
  'primary',
  'primaryHover',
  'primaryPressed',
  'onPrimary',
  'primarySurface',
  'onPrimarySurface',
  'secondary',
  'onSecondary',
  'accent',
  'onAccent',
  'border',
  'borderStrong',
  'borderFocus',
  'error',
  'onError',
  'errorSurface',
  'onErrorSurface',
  'success',
  'onSuccess',
  'successSurface',
  'onSuccessSurface',
  'warning',
  'onWarning',
  'warningSurface',
  'onWarningSurface',
  'info',
  'onInfo',
  'infoSurface',
  'onInfoSurface',
  'overlay',
  'skeleton',
] as const;
export type SemanticToken = (typeof semanticTokens)[number];

/** CSS custom-property name for a token. */
export const cssVarFor = (t: SemanticToken): string =>
  '--' + t.replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** `var(--x)` reference, for style props and CSS-in-JS. Prefer this in the DOM. */
export const v = (t: SemanticToken): string => `var(${cssVarFor(t)})`;

/** Resolved values per theme. Use ONLY where a real value is required (canvas, charts,
 *  `<meta name="theme-color">`, native platforms). */
export const themeValues = {
  light: {
    'background': '#FFFFFF',
    'surface': '#F7F8FA',
    'surfaceRaised': '#FFFFFF',
    'surfaceSunken': '#EEF0F4',
    'text.heading': '#0B0F19',
    'text.body': '#1F2430',
    'text.muted': '#5A6478',
    'text.inverse': '#FFFFFF',
    'text.disabled': '#8A93A5',
    'text.link': '#4F46E5',
    'text.linkHover': '#3730A3',
    'primary': '#4F46E5',
    'primaryHover': '#4338CA',
    'primaryPressed': '#3730A3',
    'onPrimary': '#FFFFFF',
    'primarySurface': '#EEF2FF',
    'onPrimarySurface': '#312E81',
    'secondary': '#0F766E',
    'onSecondary': '#FFFFFF',
    'accent': '#B45309',
    'onAccent': '#FFFFFF',
    'border': '#D6DAE3',
    'borderStrong': '#6B7488',
    'borderFocus': '#4F46E5',
    'error': '#B91C1C',
    'onError': '#FFFFFF',
    'errorSurface': '#FEF2F2',
    'onErrorSurface': '#991B1B',
    'success': '#15803D',
    'onSuccess': '#FFFFFF',
    'successSurface': '#F0FDF4',
    'onSuccessSurface': '#166534',
    'warning': '#92400E',
    'onWarning': '#FFFFFF',
    'warningSurface': '#FFFBEB',
    'onWarningSurface': '#854D0E',
    'info': '#1D4ED8',
    'onInfo': '#FFFFFF',
    'infoSurface': '#EFF6FF',
    'onInfoSurface': '#1E40AF',
    'overlay': 'rgba(11,15,25,0.45)',
    'skeleton': '#E7EAF0',
  },
  dark: {
    'background': '#0D1117',
    'surface': '#161B22',
    'surfaceRaised': '#1C232C',
    'surfaceSunken': '#0A0E14',
    'text.heading': '#FFFFFF',
    'text.body': '#E6EAF2',
    'text.muted': '#9BA6B8',
    'text.inverse': '#0D1117',
    'text.disabled': '#6C7686',
    'text.link': '#A5B4FC',
    'text.linkHover': '#C7D2FE',
    'primary': '#818CF8',
    'primaryHover': '#A5B4FC',
    'primaryPressed': '#C7D2FE',
    'onPrimary': '#0D1117',
    'primarySurface': '#1E1B4B',
    'onPrimarySurface': '#C7D2FE',
    'secondary': '#5EEAD4',
    'onSecondary': '#0D1117',
    'accent': '#F59E0B',
    'onAccent': '#0D1117',
    'border': '#2A313C',
    'borderStrong': '#8A94A6',
    'borderFocus': '#818CF8',
    'error': '#F87171',
    'onError': '#0D1117',
    'errorSurface': '#2A1416',
    'onErrorSurface': '#FCA5A5',
    'success': '#4ADE80',
    'onSuccess': '#0D1117',
    'successSurface': '#0F2417',
    'onSuccessSurface': '#86EFAC',
    'warning': '#FBBF24',
    'onWarning': '#0D1117',
    'warningSurface': '#2A1F06',
    'onWarningSurface': '#FDE68A',
    'info': '#60A5FA',
    'onInfo': '#0D1117',
    'infoSurface': '#0C1E36',
    'onInfoSurface': '#BFDBFE',
    'overlay': 'rgba(0,0,0,0.65)',
    'skeleton': '#232B36',
  },
} as const;

export type ThemeName = keyof typeof themeValues;

export const scales = {
  radius: {"none":"0px","sm":"6px","md":"10px","lg":"16px","xl":"24px","pill":"9999px"},
  spacing: {"0":"0px","1":"4px","2":"8px","3":"12px","4":"16px","5":"24px","6":"32px","7":"48px","8":"64px"},
  typography: {"fontFamilyBase":"system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif","fontFamilyMono":"ui-monospace, SFMono-Regular, Menlo, Consolas, monospace","size":{"caption":"12px","body":"14px","bodyLg":"16px","h3":"20px","h2":"24px","h1":"30px","hero":"38px"},"lineHeight":{"caption":"16px","body":"20px","bodyLg":"24px","h3":"28px","h2":"32px","h1":"38px","hero":"46px"},"weight":{"body":"400","medium":"500","subheading":"600","heading":"700"}},
  motion: {"duration":{"instant":"90ms","fast":"160ms","base":"260ms","slow":"420ms"},"easing":{"out":"cubic-bezier(0.16,1,0.3,1)","inOut":"cubic-bezier(0.65,0,0.35,1)","in":"cubic-bezier(0.55,0,1,0.45)"},"note":"Every animation must collapse to its END STATE under prefers-reduced-motion. Motion never gates interactivity."},
  layout: {"minSupportedWidth":"320px","contentMaxWidth":"1200px","minTouchTarget":"44px","bottomChromeHeight":"0px","bottomChromeClearance":"0px","note":"bottomChromeClearance is the ONLY number a screen may use to clear a fixed bottom bar. Never hand-pick padding."},
} as const;

/**
 * The app's installable identity, from the same generation as the manifest itself.
 *
 * The root layout needs the name, the description, the icons and the two colours. It could
 * import public/manifest.webmanifest directly - but that asks the bundler to resolve an extension it
 * does not handle by default, and the failure is a build error in every scaffolded app. It
 * could restate them, which is two sources for the app's name and therefore two names. So the
 * builder emits them here as well: one generation, two renderings, and they cannot disagree
 * because neither is written by hand.
 */
export const appManifest = {
  "id": "/",
  "name": "Default Framework App",
  "short_name": "Framework",
  "description": "An application built with the custom web app development framework.",
  "lang": "en",
  "dir": "ltr",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "display_override": [
    "window-controls-overlay",
    "standalone",
    "minimal-ui"
  ],
  "orientation": "any",
  "categories": [
    "productivity"
  ],
  "theme_color": "#FFFFFF",
  "background_color": "#FFFFFF",
  "icons": [
    {
      "src": "/brand/mark-light.svg",
      "sizes": "any",
      "type": "image/svg+xml",
      "purpose": "any"
    },
    {
      "src": "/brand/maskable-192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "/brand/maskable-512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
} as const;

/** Declared theme-aware assets, rendered by <ThemedImage />. */
export const themedAssets = {
  "logo.primary": {
    "light": "/brand/logo-light.svg",
    "dark": "/brand/logo-dark.svg",
    "alt": "Full wordmark used in the app header"
  },
  "logo.mark": {
    "light": "/brand/mark-light.svg",
    "dark": "/brand/mark-dark.svg",
    "alt": "Square app mark / favicon source"
  },
  "illustration.empty": {
    "light": "/brand/empty-light.svg",
    "dark": "/brand/empty-dark.svg",
    "alt": "Empty-state illustration"
  },
  "og.social": {
    "light": "/brand/og-card.png",
    "dark": "/brand/og-card.png",
    "alt": "Open Graph / social preview card. Fixed to the light artwork on purpose: social platforms render it on their own canvas, so it must not follow the viewer theme."
  }
} as const;
