-- =============================================================================
-- 20260925090000_jalsa_kot_item_line_order
--
-- 25-Sep correction list, item 3: items printed on the bill in the wrong order.
--
-- WHAT WAS WRONG
--   `placeRound` writes every line of a round in ONE insert, in the order the guest or captain
--   put them in the cart. Every row of that insert gets the same `created_at` (now() is the
--   transaction's start). The ticket composer ordered by `created_at` alone and the bill read
--   applied no item order at all, so a round's lines came back in whatever order Postgres and
--   PostgREST returned them - stable on a quiet table, reshuffled once rows are updated (a qty
--   change, a cancellation), which is exactly when a bill is printed.
--
-- THE FIX
--   An identity column. Postgres assigns it in the order the rows of the insert are produced,
--   which for PostgREST's bulk insert is the JSON array's order - the cart's order - for every
--   path that writes lines (guest, captain, owner, welcome drinks) without any of them changing.
--   Readers order by (created_at, line_seq): rounds in time order, lines in cart order.
--
--   Existing rows are numbered in whatever order the table holds them. That is no worse than
--   today for old rounds, and every round from this migration on is exact. Additive only.
-- =============================================================================

alter table public.kot_item
  add column if not exists line_seq bigint generated by default as identity;

create index if not exists kot_item_kot_line_idx on public.kot_item (kot_id, line_seq);
