/* GENERATED by scripts/theme-build.mjs from ../../design/tokens.json - DO NOT EDIT. */
/*
 * FIXTURE_DIVERGENCE_MARKER - LOAD-BEARING. Do not "regenerate" this file.
 *
 * This is what an app's generated theme module looks like AFTER that app has run its own
 * theme build: derived from the app's own tokens, and therefore different from the framework's
 * seed. An artifact generated from an app-owned source is app-owned too. The upgrade must skip
 * this file as expected-divergent; if it ever auto-applies the framework's copy instead, the
 * marker below disappears and conformance FAILS. That is the fixture doing its job.
 */
export const appManifest = { name: 'Diverged Fixture', short_name: 'Diverged' } as const;
